all:
	@echo "**** Compiling ITM Extension Module ****"
	$(MAKE) -C winnf/propag/itm all
	$(MAKE) -C winnf/propag/ehata all
clean:
	$(MAKE) -C winnf/propag/itm clean
	$(MAKE) -C winnf/propag/ehata clean
help:
	@echo "-- Help -- "
	@echo "  all:   Build ITM and EHata targets"
	@echo "  clean: Remove the targets and clean temp files."
